@startuml

[*] --> MENU
MENU : 1.AKU
MENU : 2.DIA
MENU --> PILIHAN
PILIHAN : MASUKKAN PILIHAN ANDA :
PILIHAN --> MENU : PILIHAN ANDA SALAH
PILIHAN --> AKU : OKE
PILIHAN --> DIA : OKE
AKU --> [*] : SELESAI
DIA --> [*] : SELESAI

@enduml